title = "Jp Lindgren Tech blog"
baseURL = "https://jplindgren.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/joao.lindgren"
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/jplindgren"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jplindgren/"
  mastodon = ""
  slack = ""
  stackoverflow = "https://stackoverflow.com/users/2497411/jplindgren"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/Neurons-in-the-brain.jpg"
  recent_posts_number = 5
  custom_css = ["css/custom-style.css"]

[taxonomies]
  category = "categories"
  tag = "tags"
