  [build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "https://jplindgren.netlify.app"
  to = "https://www.jplindgren.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.jplindgren.com/post/creating-nestjs-application/"
  to = "https://jplindgren.com/post/creating-nestjs-application-series/part1/"
  status = 301
  force = true